import { Category, Product, ProductReview } from '../types/product.types';
import { PRODUCT_IMAGES, AVATARS } from '../assets';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'all', name: 'All Products', icon: 'fa-globe', itemCount: 12, accentColor: '#6366f1' },
  { id: 'audio', name: 'Hi-Fi Audio', icon: 'fa-headphones-simple', itemCount: 3, accentColor: '#a855f7' },
  { id: 'wearables', name: 'Smart Wearables', icon: 'fa-stopwatch-20', itemCount: 3, accentColor: '#06b6d4' },
  { id: 'gaming', name: 'Gaming Rig', icon: 'fa-gamepad', itemCount: 3, accentColor: '#ec4899' },
  { id: 'smart-home', name: 'Smart Tech', icon: 'fa-house-signal', itemCount: 3, accentColor: '#10b981' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    name: 'Aura Sonic Pro Wireless Headphones',
    tagline: 'Lossless Spatial Audio with Adaptive Active Noise Cancellation',
    category: 'audio',
    price: 24999,
    originalPrice: 32499,
    discountPercent: 23,
    rating: 4.9,
    reviewCount: 428,
    image: PRODUCT_IMAGES['prod-01'].main,
    gallery: [...PRODUCT_IMAGES['prod-01'].gallery],
    description:
      'Experience studio-grade sound reproduction with precision-tuned 45mm beryllium drivers, active hybrid noise cancellation, and up to 60 hours of continuous high-fidelity playback.',
    features: [
      'Ultra-low latency Bluetooth 5.3 with LDAC support',
      'Hybrid Active Noise Cancellation (-42dB reduction)',
      'Transparency Mode with dual environmental microphones',
      'Quick charge: 10 min gives 5 hours playback',
      'Memory foam protein leather earcups',
    ],
    specs: {
      'Driver Size': '45mm Custom Beryllium',
      'Battery Life': '60 Hours (ANC Off) / 45 Hours (ANC On)',
      Weight: '248g Lightweight Alloy',
      Connectivity: 'Bluetooth 5.3 / 3.5mm Aux / USB-C Audio',
    },
    colors: ['#1e293b', '#e2e8f0', '#0284c7'],
    badge: 'HOT',
    inStock: true,
    stockCount: 18,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'prod-02',
    name: 'Chronos Ultra Titanium Smartwatch',
    tagline: 'Sapphire Crystal Display, Bio-Tracker & 14-Day Battery',
    category: 'wearables',
    price: 29999,
    originalPrice: 35999,
    discountPercent: 17,
    rating: 4.8,
    reviewCount: 312,
    image: PRODUCT_IMAGES['prod-02'].main,
    gallery: [...PRODUCT_IMAGES['prod-02'].gallery],
    description:
      'Engineered for athletes and visionaries. Chronos Ultra combines aerospace grade titanium with continuous ECG, blood oxygen telemetry, and dual-frequency GPS tracking in any environment.',
    features: [
      '1.92-inch Always-On Retina AMOLED Display (2000 nits)',
      'Grade 5 Titanium Case with Sapphire Glass',
      'ECG, SpO2, HRV & Continuous Temperature Monitoring',
      '100m Water Resistance (10 ATM & Dive Certified)',
      'Built-in Offline Topo Maps & Compass',
    ],
    specs: {
      'Case Material': 'Aerospace Titanium Grade 5',
      'Water Rating': '10 ATM (100 Meters)',
      'Battery Life': 'Up to 14 Days',
      Sensors: 'Optical Heart, ECG, SpO2, Barometer, Gyro',
    },
    colors: ['#0f172a', '#e2e8f0', '#ea580c'],
    sizes: ['44mm', '47mm'],
    badge: 'NEW',
    inStock: true,
    stockCount: 12,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'prod-03',
    name: 'Vortex RGB Mechanical Pro Keyboard',
    tagline: 'Hot-swappable Optical Switches with Gasket Mount Acoustics',
    category: 'gaming',
    price: 14999,
    originalPrice: 18999,
    discountPercent: 21,
    rating: 4.9,
    reviewCount: 518,
    image: PRODUCT_IMAGES['prod-03'].main,
    gallery: [...PRODUCT_IMAGES['prod-03'].gallery],
    description:
      'Level up your typing and competitive gaming with factory-lubed custom switches, five layers of sound dampening silicone, and vibrant per-key dynamic RGB backlighting.',
    features: [
      'CNC Anodized Aluminum Top Plate',
      'Gasket Mount Design for Creamy Acoustic Resonance',
      'Tri-Mode Wireless (2.4GHz / Bluetooth 5.1 / Type-C)',
      'Hot-swappable 5-Pin PCB Socket Support',
      'Double-shot PBT Cherry Profile Keycaps',
    ],
    specs: {
      'Switch Type': 'Linear Creamy Gold (45g Actuation)',
      'Polling Rate': '8000Hz Ultra-Response',
      'Battery Capacity': '4000mAh Rechargable',
      Layout: '75% Compact (82 Keys)',
    },
    colors: ['#1e1b4b', '#18181b', '#f8fafc'],
    badge: 'SALE',
    inStock: true,
    stockCount: 25,
    isFeatured: false,
    isTrending: true,
  },
  {
    id: 'prod-04',
    name: 'Lumix Orb 360 Smart Ambient Lamp',
    tagline: 'Circadian Light Sync & 16 Million Interactive Color Flows',
    category: 'smart-home',
    price: 9999,
    originalPrice: 12999,
    discountPercent: 22,
    rating: 4.7,
    reviewCount: 195,
    image: PRODUCT_IMAGES['prod-04'].main,
    gallery: [...PRODUCT_IMAGES['prod-04'].gallery],
    description:
      'Transform your room atmosphere with smooth organic lighting gradients, touch-capacitive gesture dimmer, music reactive rhythm mode, and integration with Alexa & Google Home.',
    features: [
      '16 Million Colors with Dynamic Fluid Scene Modes',
      'Circadian Rhythm Sunrise/Sunset Simulation',
      'Music Reactive Sound Sensor with 8 Beat Modes',
      'Matter & Apple HomeKit Certified Support',
      'Touch Ring Glow Controller',
    ],
    specs: {
      Brightness: '1200 Lumens Peak Output',
      'Power Consumption': '14W Energy Star Certified',
      Connectivity: 'Wi-Fi 6 + Bluetooth Mesh',
      Lifespan: '50,000 Hours LED Array',
    },
    colors: ['#ffffff', '#0f172a'],
    badge: 'NEW',
    inStock: true,
    stockCount: 30,
    isFeatured: false,
    isTrending: false,
  },
  {
    id: 'prod-05',
    name: 'Aura Pulse ANC Earbuds Pro',
    tagline: 'True Wireless with Wireless Qi Charging & Ceramic Drivers',
    category: 'audio',
    price: 14499,
    originalPrice: 18499,
    discountPercent: 22,
    rating: 4.9,
    reviewCount: 684,
    image: PRODUCT_IMAGES['prod-05'].main,
    gallery: [...PRODUCT_IMAGES['prod-05'].gallery],
    description:
      'Compact acoustic mastery. Crystal clear voice isolation with 6 beamforming AI microphones, dynamic bass boost, IPX7 waterproof rating, and 36 hours total battery with wireless charging case.',
    features: [
      'Dual Coaxial Driver Architecture (10mm + 6mm Planar)',
      'Smart Wind-Noise Suppression Algorithm',
      'Multipoint Seamless Device Switching',
      'IPX7 Sweat & Water Protection',
      'Wireless Fast Qi Charging Case',
    ],
    specs: {
      Playtime: '9 Hours Earbuds / 36 Hours with Case',
      'Noise Cancellation': '-48dB Ultra ANC',
      'Water Resistance': 'IPX7 Certified',
      Weight: '4.8g per Earbud',
    },
    colors: ['#0f172a', '#f8fafc', '#6366f1'],
    badge: 'HOT',
    inStock: true,
    stockCount: 40,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'prod-06',
    name: 'Phantom Wireless Gaming Mouse 8K',
    tagline: 'Ultra-lightweight 49g Shell with 8000Hz Optical Sensor',
    category: 'gaming',
    price: 10999,
    originalPrice: 13999,
    discountPercent: 22,
    rating: 4.8,
    reviewCount: 289,
    image: PRODUCT_IMAGES['prod-06'].main,
    gallery: [...PRODUCT_IMAGES['prod-06'].gallery],
    description:
      'Engineered for esports champions. Features the world-class Focus Pro 30K optical sensor, 0.2ms actuation optical switches, and zero-drag pure virgin PTFE glide feet.',
    features: [
      'Featherlight 49 Grams Solid Honeycomb Shell',
      '30,000 DPI Optical Sensor (750 IPS tracking)',
      'True 8000Hz Wireless Hyper-Polling Technology',
      'Optical Gen-3 Switches (90M clicks lifespan)',
      '100% Virgin Grade PTFE Glides',
    ],
    specs: {
      Weight: '49g Featherweight',
      Sensor: 'PAW3395 Optical 30,000 DPI',
      'Battery Life': '90 Hours Continuous Play',
      Connection: '2.4G HyperSpeed / USB-C Speedflex',
    },
    colors: ['#0f172a', '#ffffff', '#ec4899'],
    badge: 'LIMITED',
    inStock: true,
    stockCount: 14,
    isFeatured: false,
    isTrending: true,
  },
  {
    id: 'prod-07',
    name: 'NeoFit Smart Ring Genesis',
    tagline: 'Ultrathin Titanium Biometric Tracker with Sleep & Recovery Score',
    category: 'wearables',
    price: 22999,
    originalPrice: 26999,
    discountPercent: 15,
    rating: 4.7,
    reviewCount: 178,
    image: PRODUCT_IMAGES['prod-07'].main,
    gallery: [...PRODUCT_IMAGES['prod-07'].gallery],
    description:
      'Discreet and powerful wellness tracking on your finger. Monitors deep, REM, and light sleep stages, skin temperature fluctuations, daytime stress levels, and cardiovascular resilience.',
    features: [
      'Aerospace Titanium with Diamond-like Carbon Coating',
      'Medical Grade Infrared PPG Heart & SpO2 Sensor',
      'Continuous Skin Temperature Variations',
      '7-Day Battery Life on a Single 30-min Charge',
      '50m Water Resistance (Shower and Swim Safe)',
    ],
    specs: {
      Material: 'Titanium PVD Coated',
      'Water Resistance': '50 Meters (5 ATM)',
      Battery: '7 Days with Wireless Dock',
      Weight: '2.6 Grams',
    },
    colors: ['#1e293b', '#d4af37', '#cbd5e1'],
    sizes: ['Size 8', 'Size 9', 'Size 10', 'Size 11'],
    badge: 'NEW',
    inStock: true,
    stockCount: 19,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: 'prod-08',
    name: 'Aura Soundbar Cinema 5.1 Atmos',
    tagline: 'Wireless Dolby Atmos Soundbar with Dual Subwoofers',
    category: 'audio',
    price: 39999,
    originalPrice: 51999,
    discountPercent: 23,
    rating: 4.9,
    reviewCount: 387,
    image: PRODUCT_IMAGES['prod-08'].main,
    gallery: [...PRODUCT_IMAGES['prod-08'].gallery],
    description:
      'Bring the IMAX theater audio home. With upward-firing acoustic height channels, dedicated voice center channel, and room calibration AI that maps your acoustic environment in real-time.',
    features: [
      'Dolby Atmos & DTS:X 3D Spatial Audio Architecture',
      '11 Discrete Precision Amplified Speakers',
      'AI Room Calibration with Acoustic Wave Tuning',
      'HDMI eARC, Optical, AirPlay 2 & Spotify Connect',
      'Ultra-slim Low Profile Brushed Metal Housing',
    ],
    specs: {
      'Total Power Output': '520W Peak Power',
      Channels: '5.1.2 Surround System',
      Connectivity: 'HDMI eARC 4K Pass / Wi-Fi / BT 5.3',
      Dimensions: '980 x 65 x 110 mm',
    },
    colors: ['#0f172a'],
    badge: 'HOT',
    inStock: true,
    stockCount: 8,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'prod-09',
    name: 'HoloView 4K Laser Smart Projector',
    tagline: '150-inch Cinematic 4K Projection with Android TV & Auto-Focus',
    category: 'smart-home',
    price: 74999,
    originalPrice: 99999,
    discountPercent: 25,
    rating: 4.9,
    reviewCount: 315,
    image: PRODUCT_IMAGES['prod-09'].main,
    gallery: [...PRODUCT_IMAGES['prod-09'].gallery],
    description:
      'Transform any blank wall into a 150-inch 4K laser cinema. Features instant auto-keystone correction, 2500 ANSI Lumens brightness, built-in Harman Kardon speakers, and Netflix certified.',
    features: [
      'True 4K UHD Resolution (3840 x 2160) with HDR10+',
      '2500 ANSI Lumens ALPD 4.0 Laser Light Engine',
      'Intelligent Instant Auto-Keystone & Obstacle Avoidance',
      'Dual 15W Harman Kardon Integrated Sound',
      'Built-in Android TV 12 with Google Play Store',
    ],
    specs: {
      Resolution: '4K UHD (3840 x 2160)',
      Brightness: '2500 ANSI Lumens',
      'Lamp Life': '30,000 Hours',
      'Screen Size': '40 to 150 Inches',
    },
    colors: ['#334155', '#f8fafc'],
    badge: 'HOT',
    inStock: true,
    stockCount: 6,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'prod-10',
    name: 'AeroStream Pro Mesh Wi-Fi 7 Router',
    tagline: 'BE19000 Tri-Band Multi-Gigabit Wireless Network',
    category: 'smart-home',
    price: 19999,
    originalPrice: 24999,
    discountPercent: 20,
    rating: 4.8,
    reviewCount: 142,
    image: PRODUCT_IMAGES['prod-10'].main,
    gallery: [...PRODUCT_IMAGES['prod-10'].gallery],
    description:
      'Eliminate dead zones and buffer lag across your entire home. Supports up to 250 connected devices simultaneously with ultra-wide 320MHz channels and 10Gbps Ethernet WAN/LAN ports.',
    features: [
      'Next-Gen Wi-Fi 7 (802.11be) Tri-Band Speeds up to 19Gbps',
      'Ultra-wide 320MHz Channels & Multi-Link Operation (MLO)',
      'Covers up to 6,500 sq. ft with 2-pack Mesh node',
      '2x 10Gbps Multi-Gigabit Ethernet Ports',
      'Built-in HomeShield AI Network Security',
    ],
    specs: {
      'Wi-Fi Speed': '19 Gbps Combined Tri-Band',
      Coverage: 'Up to 6,500 sq ft',
      Ports: '2x 10G WAN/LAN + 4x 2.5G LAN',
      Capacity: '250+ Concurrent Devices',
    },
    colors: ['#ffffff', '#0f172a'],
    badge: 'NEW',
    inStock: true,
    stockCount: 22,
    isFeatured: false,
    isTrending: false,
  },
  {
    id: 'prod-11',
    name: 'Titan Stealth Carbon Fiber Controller',
    tagline: 'Hall Effect Magnetic Sticks, Mechanical Tactile D-Pad & Trigger Locks',
    category: 'gaming',
    price: 12999,
    originalPrice: 15999,
    discountPercent: 20,
    rating: 4.9,
    reviewCount: 461,
    image: PRODUCT_IMAGES['prod-11'].main,
    gallery: [...PRODUCT_IMAGES['prod-11'].gallery],
    description:
      'Say goodbye to stick drift forever. Featuring contactless electromagnetic Hall Effect joysticks, 4 remappable rear paddles, adjustable hair-trigger locks, and rubberized diamond grip.',
    features: [
      'Hall Effect Anti-Drift Contactless Magnetic Sensors',
      '4 Remappable Ergonomic Back Paddles',
      'Microswitch Mechanical Face Buttons (5M clicks)',
      '3-Way Hair Trigger Physical Slide Locks',
      'Compatible with PC, PS5, Xbox Series & Switch',
    ],
    specs: {
      Battery: '1200mAh (20 Hours Playtime)',
      Latency: '0.5ms Wireless Polling',
      Weight: '235g Balanced Ergonomics',
      Software: 'Aura Command Customizer',
    },
    colors: ['#0f172a', '#dc2626', '#4f46e5'],
    badge: 'SALE',
    inStock: true,
    stockCount: 35,
    isFeatured: false,
    isTrending: true,
  },
  {
    id: 'prod-12',
    name: 'PulseBand Dynamic Fitness Tracker',
    tagline: 'Curved AMOLED Display, 24/7 Heart & Oxygen Vital Tracker',
    category: 'wearables',
    price: 6999,
    originalPrice: 9499,
    discountPercent: 26,
    rating: 4.6,
    reviewCount: 230,
    image: PRODUCT_IMAGES['prod-12'].main,
    gallery: [...PRODUCT_IMAGES['prod-12'].gallery],
    description:
      'Sleek, lightweight, and packed with health intelligence. 120+ workout sport modes, sleep quality assessment, stress breathing exercises, and 16-day ultra endurance battery life.',
    features: [
      '1.62-inch High-Res Curved AMOLED Touchscreen',
      '120+ Professional Fitness & Sport Activity Tracking',
      'All-Day Continuous Blood Oxygen (SpO2) & Stress',
      '5ATM Water Resistance (Shower & Swim Proof)',
      'Magnetic Snap Fast Charging',
    ],
    specs: {
      Display: '1.62" AMOLED 326 PPI',
      'Battery Life': '16 Days Typical Usage',
      Weight: '13.5g Featherweight Strap',
      'Water Rating': '5 ATM (50m)',
    },
    colors: ['#0f172a', '#10b981', '#f43f5e'],
    badge: 'LIMITED',
    inStock: true,
    stockCount: 50,
    isFeatured: false,
    isTrending: false,
  },
];

export const MOCK_REVIEWS: ProductReview[] = [
  {
    id: 'rev-1',
    userName: 'Marcus Vance',
    userAvatar: AVATARS.marcusVance,
    rating: 5,
    date: '2 days ago',
    comment:
      'Absolutely blown away by the build quality and spatial audio clarity. The bass response is tight and impactful without muddying the mids. Best purchase this year!',
    verifiedPurchase: true,
  },
  {
    id: 'rev-2',
    userName: 'Sophia Chen',
    userAvatar: AVATARS.sophiaChen,
    rating: 5,
    date: '1 week ago',
    comment:
      'The design aesthetics are sublime! Fast shipping, sleek unboxing experience, and the battery life matches the advertised specs effortlessly.',
    verifiedPurchase: true,
  },
  {
    id: 'rev-3',
    userName: 'Alexander Wright',
    userAvatar: AVATARS.alexanderWright,
    rating: 4,
    date: '2 weeks ago',
    comment:
      'Super crisp resolution and premium material finish. The companion app connectivity is instant and intuitive.',
    verifiedPurchase: true,
  },
];

export const ProductService = {
  MOCK_PRODUCTS,
  MOCK_CATEGORIES,
  MOCK_REVIEWS,

  async getCategories(): Promise<Category[]> {
    return MOCK_CATEGORIES;
  },

  async getProducts(): Promise<Product[]> {
    return MOCK_PRODUCTS;
  },

  async getProductById(id: string): Promise<Product | undefined> {
    return MOCK_PRODUCTS.find((p) => p.id === id);
  },

  async getProductReviews(_productId: string): Promise<ProductReview[]> {
    return MOCK_REVIEWS;
  },
};
